[workspace]

members = [
    "hakim-engine",
    "hakim-cli",
    "hakim-wasm",
    "hakim-json",
    "hakim-server",
]

[profile.release.package.hakim-wasm]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
