[package]
name = "hakim-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hakim-engine = { path = "../hakim-engine" }
rustyline = "9.0.0"
