[package]
name = "hakim-json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.150"
serde_json = "1.0.89"
hakim-engine = { path = "../hakim-engine" }
