# This is a basic workflow to help you get started with Actions

name: build_example_web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_server:
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
          - build: macos
            os: macos-latest
          - build: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang # required for bindgen to work, see https://github.com/rust-lang/rust-bindgen/issues/1797
        uses: KyleMayes/install-llvm-action@v1
        if: matrix.os == 'windows-latest'
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'
      - name: Build hakim_server
        run: |
          cd hakim-server
          cargo build --release
      - name: Upload artifacts
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: hakim-server
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # enable in wasm mode:
      # - name: Build wasm
      #   run: |
      #     cd hakim-json
      #     EMCC_CFLAGS="-s TOTAL_STACK=32MB" cargo build -vv --release --target wasm32-unknown-emscripten
      #     cd ..
      #     node scripts/patch-emscripten.js ./target/wasm32-unknown-emscripten/release/hakim-json.js
      #     cp ./target/wasm32-unknown-emscripten/release/hakim-json.js ./front/static/.
      #     cp ./target/wasm32-unknown-emscripten/release/hakim_json.wasm ./front/static/.

      # Runs a set of commands using the runners shell
      - name: Build www
        run: |
          cd front
          npm install -g yarn
          yarn
          yarn build
          echo "proof.babaeee.ir" > dist/CNAME
          echo "" > dist/.nojekyll
          cat dist/index.html > dist/404.html

      - name: Deploy to github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          build_dir: front/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
