name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches: ["main"]

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      # enable in wasm mode:
      # - name: Build wasm
      #   run: |
      #     cd hakim-json
      #     EMCC_CFLAGS="-s TOTAL_STACK=32MB" cargo build -vv --release --target wasm32-unknown-emscripten
      #     cd ..
      #     node scripts/patch-emscripten.js ./target/wasm32-unknown-emscripten/release/hakim-json.js
      #     cp ./target/wasm32-unknown-emscripten/release/hakim-json.js ./front/static/.
      #     cp ./target/wasm32-unknown-emscripten/release/hakim_json.wasm ./front/static/.
      - name: Build www
        run: |
          cd front
          npm install -g yarn
          yarn
          yarn build
          cat dist/index.html > dist/404.html
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: |
          cd front
          cd dist
          vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
