name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
      - name: Check clippy warnings
        run: cargo clippy -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
      - name: Check formatting of all crates in the workspace
        run: cargo fmt --all -- --check
